sms/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('supply.urls')),  # Include the supply app URLs
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supply/urls.py
from django.urls import path
from supply import views
from supply.views import (
    CustomerPendingRequestListView,
    SupplyItemListView,
    SupplierProfileDetailView,
    SupplyItemTransactionListView,      
    SupplyManagerProfileDetailView,
    update_supply_manager_profile,
    CustomerSupplyRequestListView

)

app_name = 'supply'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path("logout/", views.logout_user, name="logout"),
    path("access_denied/", views.access_denied, name="access_denied"),

    # SupplyItem URLs
    path('supplyitem/create/', views.create_supply_item, name='create_supply_item'),
    path('supplyitem/lists', SupplyItemListView.as_view(), name='supplyitem_list'),
    path('supplyitem/<int:pk>/', views.SupplyItemDetailView.as_view(), name='supplyitem_detail'),
    path('supplyitem/<int:pk>/transaction/recieved/', views.supplyitem_transaction_receive, name='supplyitem_transaction_receive'),
    path('supplyitem/<int:pk>/transaction/deliver/', views.supplyitem_transaction_deliver, name='supplyitem_transaction_deliver'),
    path('supplyitem/<int:pk>/edit/', views.edit_supply_item, name='edit_supply_item'),
    
    # Supplier URLs
    path('supplier/login/', views.supplier_login, name='supplier_login'),
    path('supplier/register/', views.supplier_registration, name='supplier_registration'),
    path('supplier/profile/<pk>/', SupplierProfileDetailView.as_view(), name='supplier_profile_detail'),
    path('supplier/choose-items/', views.supplier_choose_items, name='supplier_choose_items'),
    path('supplier/remove-items/', views.supplier_remove_items, name='supplier_remove_items'),
    
    # SupplyManager URLs
    path('supplymanager/login/', views.supply_manager_login, name='supplymanager_login'),
    path('supplymanager/profile/update/', update_supply_manager_profile, name='update_supply_manager_profile'),
    path('supplymanager/register/', views.supply_manager_registration, name='supplymanager_registration'),
    #path('supply_manager/profile/', supply_manager_profile_detail, name='supply_manager_profile_detail'),
    path('supplymanager/profile/<pk>/', SupplyManagerProfileDetailView.as_view(), name='supplymanager_profile_detail'),
    path('supplymanager/supply-requests/pending/', 
        CustomerPendingRequestListView.as_view(),
        name='customer_pending_requests'),
    path('supply-request/<int:pk>/approve/', views.approve_request, name='approve_request'),
    path('supply-request/<int:pk>/reject/', views.reject_request, name='reject_request'),

    # Supply Item Transaction History
    path('supplyitem/transactions', SupplyItemTransactionListView.as_view(), name='supplyitem_transaction'),
    
    # Customer URLS
    path('customer/login/', views.customer_login, name='customer_login'),
    path('customer/register/', views.customer_registration, name='customer_registration'),
    path('requestable-supply/', views.customer_requestable_supply, name='customer_requestable_supply'),
    path('request-supply/<int:item_id>/', views.request_supply_item, name='request_supply_item'),
    path('customer/supply-requests/', 
        CustomerSupplyRequestListView.as_view(), 
        name='customer_supply_request_list'),
    
    path('transaction/<int:pk>/complete/', views.complete_transaction, name='complete_transaction'),
]

assets/templates/partials/sidebars/_customer_sidebar.html
{% load static %}


          <li class="nav-item nav-category">
            <span class="nav-link">Navigation</span>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'supply:customer_requestable_supply' %}">
              <span class="menu-icon">
                <i class="mdi mdi-chip"></i>
              </span>
              <span class="menu-title">Available Supplies</span>
            </a>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'supply:customer_supply_request_list' %}">
              <span class="menu-icon">
                <i class="mdi mdi-chip"></i>
              </span>
              <span class="menu-title">My Requests</span>
            </a>
          </li>





      <!-- partial -->

assets/templates/partials/sidebars/_supply_manager_sidebar.html
          <li class="nav-item nav-category">
            <span class="nav-link">Navigation</span>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'supply:supplyitem_transaction' %}">
              <span class="menu-icon">
                <i class="mdi mdi-chip"></i>
              </span>
              <span class="menu-title">Supply Transactions</span>
            </a>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'supply:customer_pending_requests' %}">
              <span class="menu-icon">
                <i class="mdi mdi-playlist-play"></i>
              </span>
              <span class="menu-title">Pending Requests</span>
            </a>
          </li>

          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'supply:customer_pending_requests' %}">
              <span class="menu-icon">
                <i class="mdi mdi-playlist-play"></i>
              </span>
              <span class="menu-title">Customer Requests</span>
            </a>
          </li>